global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-boot-app'
    metrics_path: '/log-ex/actuator/prometheus'
    static_configs:
      - targets: ['log-example-app:9090']